package com.mercadolibre.android.andesui.radiobuttongroup.distribution

internal sealed class AndesRadioButtonGroupDistributionInterface

internal object AndesRadioButtonGroupVertical : AndesRadioButtonGroupDistributionInterface()

internal object AndesRadioButtonGroupHorizontal : AndesRadioButtonGroupDistributionInterface()
